<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-26T22:32:32 BDT" name="Default suite" finished-at="2024-02-26T22:33:00 BDT" duration-ms="28774">
    <groups>
    </groups>
    <test started-at="2024-02-26T22:32:32 BDT" name="Default test" finished-at="2024-02-26T22:33:00 BDT" duration-ms="28774">
      <class name="DemoProjectExtent.Futurenation">
        <test-method is-config="true" signature="ExtxtsetUp()[pri:0, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:32:31 BDT" name="ExtxtsetUp" finished-at="2024-02-26T22:32:32 BDT" duration-ms="322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ExtxtsetUp -->
        <test-method is-config="true" signature="url()[pri:0, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:32:32 BDT" name="url" finished-at="2024-02-26T22:32:38 BDT" duration-ms="6729" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- url -->
        <test-method signature="invalidsignup()[pri:1, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:32:38 BDT" name="invalidsignup" description="Invalid Email and Valid Password" finished-at="2024-02-26T22:32:45 BDT" duration-ms="6687" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Email required] but found [invalid email]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Email required] but found [invalid email]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at DemoProjectExtent.Futurenation.invalidsignup(Futurenation.java:122)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidsignup -->
        <test-method is-config="true" signature="tearDown1()[pri:0, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:32:45 BDT" name="tearDown1" finished-at="2024-02-26T22:32:45 BDT" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown1 -->
        <test-method is-config="true" signature="url()[pri:0, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:32:45 BDT" name="url" finished-at="2024-02-26T22:32:51 BDT" duration-ms="6174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- url -->
        <test-method signature="validSignin()[pri:1, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:32:51 BDT" name="validSignin" description="valid Email and password" finished-at="2024-02-26T22:33:00 BDT" duration-ms="8784" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validSignin -->
        <test-method is-config="true" signature="tearDown1()[pri:0, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:33:00 BDT" name="tearDown1" finished-at="2024-02-26T22:33:00 BDT" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown1 -->
        <test-method is-config="true" signature="tearDwon()[pri:0, instance:DemoProjectExtent.Futurenation@13c9d689]" started-at="2024-02-26T22:33:00 BDT" name="tearDwon" finished-at="2024-02-26T22:33:01 BDT" duration-ms="485" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDwon -->
      </class> <!-- DemoProjectExtent.Futurenation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
